using System.Text.RegularExpressions;
using EchoPBX.Data.Models;

namespace EchoPBX.Data.Services.CallFlows;

/// <summary>
/// Turns a <see cref="CallFlowDefinition"/> into the lines of an extensions.conf context.
/// </summary>
/// <remarks>
/// A dialplan context is already a top-down script, so a flow maps onto one almost directly:
/// every reachable node becomes a labelled priority on extension <c>s</c>, and every edge
/// becomes a <c>Goto</c>.
/// <para>
/// This is deliberately a pure function - no database, no filesystem, no Asterisk - so the
/// riskiest part of the feature can be exercised without a running PBX.
/// </para>
/// </remarks>
public static partial class CallFlowDialplanBuilder
{
    /// <summary>
    /// The context a flow is generated into.
    /// </summary>
    public static string ContextName(string slug) => $"callflow-{slug}";

    /// <summary>
    /// Builds the <c>[callflow-{slug}]</c> context for a single flow. Always returns a valid
    /// context, even when the flow is empty or malformed, so a bad flow can never take the
    /// rest of the dialplan down with it.
    /// </summary>
    /// <param name="queueIds">The queues that exist. A flow still pointing at a deleted queue
    /// ends the call there instead of jumping to an extension that is gone.</param>
    public static List<string> Build(int id, string slug, string name, CallFlowDefinition definition,
        IReadOnlySet<int> queueIds)
    {
        var context = ContextName(slug);
        var lines = new List<string>
        {
            ";=============================================",
            $"; Call flow {id} - {name}",
            ";=============================================",
            "",
            $"[{context}]",
            $"exten => s,1,NoOp(EchoPBX call flow: {Sanitize(name)})",
            " same => n,Answer()",
        };

        // Walk the graph breadth-first from the start node, giving each node it reaches a
        // positional label. Labels are handed out by visit order rather than derived from the
        // node ids, so ids generated by the dashboard never have to be sanitized into
        // something Asterisk accepts.
        var start = definition.Nodes.FirstOrDefault(x => x is StartNode);
        if (start == null)
        {
            lines.Add(" same => n,Hangup()");
            lines.Add("");
            return lines;
        }

        var nodesById = definition.Nodes
            .GroupBy(x => x.Id)
            .ToDictionary(g => g.Key, g => g.First());

        var labels = new Dictionary<string, string>();
        var order = new List<CallFlowNode>();
        var queue = new Queue<CallFlowNode>();
        queue.Enqueue(start);
        labels[start.Id] = "node_0";

        while (queue.Count > 0)
        {
            var node = queue.Dequeue();
            order.Add(node);

            foreach (var edge in OutgoingEdges(definition, node.Id))
            {
                if (!nodesById.TryGetValue(edge.Target, out var target)) continue;
                if (labels.ContainsKey(target.Id)) continue; // already queued, an edge back to it is just a Goto

                labels[target.Id] = $"node_{labels.Count}";
                queue.Enqueue(target);
            }
        }

        lines.Add($" same => n,Goto({labels[start.Id]})");
        lines.Add("");

        string? TargetLabel(CallFlowEdge? edge) =>
            edge != null && labels.TryGetValue(edge.Target, out var target) ? target : null;

        foreach (var node in order)
        {
            var label = labels[node.Id];
            var outgoing = OutgoingEdges(definition, node.Id).ToArray();
            var body = new List<string>();

            // The line followed once the step is done: the default branch of a menu, or the only
            // output of anything else.
            var next = node is MenuNode
                ? outgoing.FirstOrDefault(x => x.SourceHandle == MenuNode.NoChoiceHandle)
                : outgoing.FirstOrDefault();

            switch (node)
            {
                case StartNode:
                    body.Add($" same => n({label}),NoOp(Start)");
                    break;

                case PlaybackNode playback when !string.IsNullOrWhiteSpace(playback.Sound):
                    lines.Add("; Play sound");
                    body.Add($" same => n({label}),Playback({Sanitize(playback.Sound)})");
                    break;

                case PlaybackNode:
                    // Configured but no sound picked yet - keep the flow walkable.
                    lines.Add("; Play sound (no sound selected)");
                    body.Add($" same => n({label}),NoOp(No sound selected)");
                    break;

                case HangupNode:
                    lines.Add("; Hang up");
                    body.Add($" same => n({label}),Hangup()");
                    break;

                case QueueNode { QueueId: { } queueId } when queueIds.Contains(queueId):
                    // The entry point the test call uses too, so the queue's announcement plays.
                    lines.Add("; Go to queue");
                    body.Add($" same => n({label}),Goto(system,queue-{queueId},1)");
                    break;

                case QueueNode:
                    lines.Add("; Go to queue (no queue selected)");
                    body.Add($" same => n({label}),NoOp(No queue selected)");
                    body.Add(" same => n,Hangup()");
                    break;

                case MenuNode menu:
                    lines.Add("; Menu");
                    body.AddRange(BuildMenu(label, menu, outgoing, TargetLabel));
                    break;

                default:
                    body.Add($" same => n({label}),NoOp(Unsupported step)");
                    break;
            }

            // Every edge gets an explicit Goto even when it points at the very next line. One
            // spare priority buys a generator that does not care what order nodes are emitted in.
            if (node is not (HangupNode or QueueNode))
            {
                if (TargetLabel(next) is { } targetLabel)
                {
                    body.Add($" same => n,Goto({targetLabel})");
                }
                else
                {
                    // Nothing follows this step, so end the call rather than letting it fall
                    // off the end of the context.
                    body.Add(" same => n,Hangup()");
                }
            }

            lines.AddRange(body);
            lines.Add("");
        }

        return lines;
    }

    /// <summary>
    /// Reads one key and jumps to the branch for it. A caller who presses nothing or an unknown
    /// key hears the prompt again, and after the last attempt falls through to the default
    /// branch, which the caller of this method adds.
    /// </summary>
    /// <remarks>
    /// Read() rather than Background() and WaitExten(), so the whole menu lives on extension
    /// <c>s</c> like every other step, and two menus in one flow never compete for the same
    /// digit extensions. The <c>e</c> option hands back <c>#</c> as the value when it is the only
    /// key pressed, instead of treating it as an empty entry, so <c>#</c> works as a menu key.
    /// The variables can be shared by every menu because a menu resets them on entry and only
    /// one runs at a time.
    /// </remarks>
    private static IEnumerable<string> BuildMenu(string label, MenuNode menu, CallFlowEdge[] outgoing,
        Func<CallFlowEdge?, string?> targetLabel)
    {
        yield return $" same => n({label}),Set(MENU_ATTEMPT=0)";
        yield return $" same => n({label}_ask),Read(MENU_CHOICE,{Sanitize(menu.Sound)},1,e,1,{menu.Timeout})";

        foreach (var key in menu.Options.Where(MenuNode.IsKey).Distinct())
        {
            var condition = $"$[\"${{MENU_CHOICE}}\" = \"{key}\"]";

            // A key without anything connected ends the call, like the end of any other line.
            yield return targetLabel(outgoing.FirstOrDefault(x => x.SourceHandle == key)) is { } target
                ? $" same => n,GotoIf({condition}?{target})"
                : $" same => n,ExecIf({condition}?Hangup())";
        }

        yield return " same => n,ExecIf($[\"${MENU_CHOICE}\" != \"\"]?Playback(pm-invalid-option))";
        yield return " same => n,Set(MENU_ATTEMPT=$[${MENU_ATTEMPT} + 1])";
        yield return $" same => n,GotoIf($[${{MENU_ATTEMPT}} < {menu.Attempts}]?{label}_ask)";
    }

    /// <summary>
    /// The edges leaving a node, ordered so generation is deterministic.
    /// </summary>
    private static IEnumerable<CallFlowEdge> OutgoingEdges(CallFlowDefinition definition, string nodeId) =>
        definition.Edges
            .Where(x => x.Source == nodeId)
            .OrderBy(x => x.SourceHandle ?? "", StringComparer.Ordinal);

    /// <summary>
    /// Strips the characters that would end an application's argument list early or start a
    /// comment, so a name typed in the dashboard cannot break the generated dialplan.
    /// </summary>
    private static string Sanitize(string? value) => UnsafeCharacters().Replace(value ?? "", "");

    [GeneratedRegex(@"[,;()\[\]\r\n]")]
    private static partial Regex UnsafeCharacters();
}
