using System.Text.Json;
using System.Text.Json.Serialization;

namespace EchoPBX.Data.Models;

/// <summary>
/// The graph stored in <see cref="CallFlow.DefinitionJson"/>. Node positions are not stored:
/// the dashboard lays the graph out automatically every time it renders.
/// </summary>
public class CallFlowDefinition
{
    public List<CallFlowNode> Nodes { get; set; } = [];

    public List<CallFlowEdge> Edges { get; set; } = [];

    /// <summary>
    /// The options used to read and write <see cref="CallFlow.DefinitionJson"/>. camelCase so
    /// the stored document matches what the dashboard sends and receives.
    /// </summary>
    public static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static CallFlowDefinition Parse(string json)
    {
        if (string.IsNullOrWhiteSpace(json)) return new CallFlowDefinition();

        try
        {
            return JsonSerializer.Deserialize<CallFlowDefinition>(json, JsonOptions) ?? new CallFlowDefinition();
        }
        catch (JsonException)
        {
            return new CallFlowDefinition();
        }
    }

    public string Serialize() => JsonSerializer.Serialize(this, JsonOptions);
}

/// <summary>
/// One card in the flow. The <c>type</c> discriminator decides which subclass is used.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(StartNode), "start")]
[JsonDerivedType(typeof(PlaybackNode), "playback")]
[JsonDerivedType(typeof(HangupNode), "hangup")]
[JsonDerivedType(typeof(MenuNode), "menu")]
[JsonDerivedType(typeof(QueueNode), "queue")]
public abstract class CallFlowNode
{
    /// <summary>
    /// Identifier generated by the dashboard. Unique within the flow.
    /// </summary>
    public string Id { get; set; } = null!;
}

/// <summary>
/// Where every call through this flow begins. Exactly one per flow, and it cannot be deleted.
/// </summary>
public class StartNode : CallFlowNode;

/// <summary>
/// Ends the call.
/// </summary>
public class HangupNode : CallFlowNode;

/// <summary>
/// Hands the call to a queue. The call leaves the flow there, so nothing can follow this step.
/// </summary>
public class QueueNode : CallFlowNode
{
    public int? QueueId { get; set; }
}

/// <summary>
/// A step that plays a sound, so uploaded audio is stored the same way whichever step uses it.
/// </summary>
public interface ISoundNode
{
    string Id { get; }

    SoundKind Kind { get; set; }

    /// <inheritdoc cref="PlaybackNode.Sound"/>
    string? Sound { get; set; }
}

/// <summary>
/// Plays an audio file to the caller and continues.
/// </summary>
public class PlaybackNode : CallFlowNode, ISoundNode
{
    public SoundKind Kind { get; set; } = SoundKind.Upload;

    /// <summary>
    /// For <see cref="SoundKind.Upload"/> this is a data URL on the way in, the absolute path
    /// without the .wav suffix once stored, and a /sounds/... URL on the way back out.
    /// For <see cref="SoundKind.Builtin"/> it is the Asterisk sound name, unchanged everywhere.
    /// </summary>
    public string? Sound { get; set; }
}

/// <summary>
/// Plays a prompt and branches on the key the caller presses, like a switch statement. Every key
/// in <see cref="Options"/> is an output of its own, and <see cref="NoChoiceHandle"/> is the
/// default branch, followed once the caller has used up <see cref="Attempts"/> without pressing
/// a valid key.
/// </summary>
public class MenuNode : CallFlowNode, ISoundNode
{
    public const string NoChoiceHandle = "none";

    /// <summary>
    /// Whether the caller can press this key. Nothing else ever reaches the dialplan.
    /// </summary>
    public static bool IsKey(string? key) => key is { Length: 1 } && "0123456789*#".Contains(key[0]);

    public SoundKind Kind { get; set; } = SoundKind.Upload;

    /// <inheritdoc cref="PlaybackNode.Sound"/>
    public string? Sound { get; set; }

    /// <summary>
    /// The keys the caller can press: digits, <c>*</c> and <c>#</c>.
    /// </summary>
    public List<string> Options { get; set; } = [];

    /// <summary>
    /// Seconds to wait for a key once the prompt has finished.
    /// </summary>
    public int Timeout { get; set; } = 5;

    /// <summary>
    /// How often the prompt is played before the default branch is followed.
    /// </summary>
    public int Attempts { get; set; } = 3;
}

/// <summary>
/// A line between two cards. <see cref="SourceHandle"/> is "next" for steps with a single
/// output, and for a <see cref="MenuNode"/> either a key or <see cref="MenuNode.NoChoiceHandle"/>.
/// </summary>
public class CallFlowEdge
{
    public string Id { get; set; } = null!;

    public string Source { get; set; } = null!;

    public string Target { get; set; } = null!;

    public string? SourceHandle { get; set; }
}

public enum SoundKind
{
    /// <summary>An audio file uploaded through the dashboard.</summary>
    Upload = 1,

    /// <summary>One of the sounds that ships with Asterisk.</summary>
    Builtin = 2,
}
