// <auto-generated />
using System;
using EchoPBX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoPBX.Data.Migrations
{
    [DbContext(typeof(EchoDbContext))]
    [Migration("20260131133036_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("EchoPBX.Data.Models.AccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("access_tokens");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Cdr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmaFlags")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Answer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clid")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationChannel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationContext")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("End")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAppArguments")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAppExecuted")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("Start")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("cdr");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.DtmfMenuEntry", b =>
                {
                    b.Property<int>("TrunkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Digit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrunkId", "Digit");

                    b.HasIndex("QueueId");

                    b.ToTable("dtmf_menu_entries");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Extension", b =>
                {
                    b.Property<int>("ExtensionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxDevices")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutgoingTrunkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ExtensionNumber");

                    b.HasIndex("OutgoingTrunkId");

                    b.ToTable("extensions");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Announcement")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicOnHold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrapUpTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("queues");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.QueueExtension", b =>
                {
                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtensionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueueId", "ExtensionNumber");

                    b.HasIndex("ExtensionNumber");

                    b.ToTable("queue_extensions");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.SystemSetting", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("system_settings");

                    b.HasData(
                        new
                        {
                            Name = "DashboardLanguage",
                            Id = 0,
                            Value = "en"
                        },
                        new
                        {
                            Name = "AsteriskLanguage",
                            Id = 0,
                            Value = "en"
                        });
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Trunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codecs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DtmfAnnouncement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomingCallBehaviour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.ToTable("trunks");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.TrunkExtension", b =>
                {
                    b.Property<int>("TrunkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtensionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrunkId", "ExtensionNumber");

                    b.HasIndex("ExtensionNumber");

                    b.ToTable("trunk_extensions");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.AccessToken", b =>
                {
                    b.HasOne("EchoPBX.Data.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.DtmfMenuEntry", b =>
                {
                    b.HasOne("EchoPBX.Data.Models.Queue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoPBX.Data.Models.Trunk", "Trunk")
                        .WithMany("DtmfMenuEntries")
                        .HasForeignKey("TrunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");

                    b.Navigation("Trunk");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Extension", b =>
                {
                    b.HasOne("EchoPBX.Data.Models.Trunk", "OutgoingTrunk")
                        .WithMany()
                        .HasForeignKey("OutgoingTrunkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OutgoingTrunk");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.QueueExtension", b =>
                {
                    b.HasOne("EchoPBX.Data.Models.Extension", "Extension")
                        .WithMany("Queues")
                        .HasForeignKey("ExtensionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoPBX.Data.Models.Queue", "Queue")
                        .WithMany("Extensions")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Trunk", b =>
                {
                    b.HasOne("EchoPBX.Data.Models.Queue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.TrunkExtension", b =>
                {
                    b.HasOne("EchoPBX.Data.Models.Extension", "Extension")
                        .WithMany()
                        .HasForeignKey("ExtensionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoPBX.Data.Models.Trunk", "Trunk")
                        .WithMany()
                        .HasForeignKey("TrunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("Trunk");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Extension", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Queue", b =>
                {
                    b.Navigation("Extensions");
                });

            modelBuilder.Entity("EchoPBX.Data.Models.Trunk", b =>
                {
                    b.Navigation("DtmfMenuEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
